# Generated by Django 5.2.7 on 2025-11-19 15:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('sin stock', 'Sin Stock')], default='disponible', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('estadoReparacion', models.CharField(max_length=100)),
                ('descripcionProblema', models.CharField(max_length=100)),
                ('observacionesMecanico', models.CharField(max_length=100)),
                ('idMaquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinas.maquina')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepuestoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.PositiveIntegerField()),
                ('precio_unitario_al_momento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinas.reparacion')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinas.repuesto')),
            ],
            options={
                'db_table': 'Repuestos_Reparaciones',
                'unique_together': {('repuesto', 'reparacion')},
            },
        ),
    ]
