# Generated by Django 5.2.7 on 2025-11-04 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_permiso_rol_usuariorol_usuario_roles_rolpermiso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolpermiso',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_asignados', to='usuarios.rol'),
        ),
    ]
